### PR TITLE
fix: more information about container-registry credential sourcing

### PR DESCRIPTION
**Pull request by shreddedbacon**
Just some minor changes to the output of custom container registry information to display where the credential was sourced from to aid in debugging if required.

Also adds some header separators for the UI to split up sections

### CODE REVIEW

**Comment by shreddedbacon** [comment]
Do we close out this one and #132 in favor of #133 (with the suggested fixes from #132)?

**Comment by tobybellwood** [comment]
> Do we close out this one and #132 in favor of #133 (with the suggested fixes from #132)?

If 133 is the complete package, lets just do that one?

**Comment by shreddedbacon** [comment]
Closing in favor of #133

**Comment by shreddedbacon** [comment]
Reopening, #133 contains other PRs not confirmed for merging yet

**Comment by shreddedbacon** [comment]
#132 contains this PR in it, so closing this again :facepalm:

**Pull request closed without merging**
