### PR TITLE
Rebuild kubectl-build-deploy dind from this repo

### PR DESCRIPTION
**Pull request by tobybellwood**
This PR transfers the build process used to create the uselagoon/kubectl-build-deploy-dind image into this repo, so that the build and its resultant image may be released together, on a more regular schedule.

Over time, as #27 is completed, less code will be in the /legacy folder, until the entire process is replaced.

Here is a diff of the most recent build compared to the last released - there are only the three binary differences - envsubst and syft are to be expected, and the change to build-deploy-tool is minimal
```

-----File-----

These entries have been added to uselagoon/kubectl-build-deploy-dind:v2.9.1:
FILE                                                                                            SIZE
/home/.cache/pip/http/5/a                                                                       1.2M
/home/.cache/pip/http/5/a/0                                                                     1.2M
/home/.cache/pip/http/5/a/0/8                                                                   1.2M
/home/.cache/pip/http/5/a/0/8/e                                                                 1.2M
/home/.cache/pip/http/5/a/0/8/e/5a08ef2ee9b3927f2573cf9faeadaa4fe742be01ea848922c2c64893        1.2M

These entries have been deleted from uselagoon/kubectl-build-deploy-dind:v2.9.1:
FILE                                                                                            SIZE
/home/.cache/pip/http/6                                                                         1.2M
/home/.cache/pip/http/6/8                                                                       1.2M
/home/.cache/pip/http/6/8/0                                                                     1.2M
/home/.cache/pip/http/6/8/0/5                                                                   1.2M
/home/.cache/pip/http/6/8/0/5/9                                                                 1.2M
/home/.cache/pip/http/6/8/0/5/9/680599efb54b31092d09aed2ae4b826419e945b2c1d40b17696d8823        1.2M

These entries have been changed between uselagoon/kubectl-build-deploy-dind:v2.9.1 and ghcr.io/uselagoon/build-deploy-image:build-image:
FILE                                                                                                                             SIZE1         SIZE2
/usr/local/bin/syft                                                                                                              58.9M         57.2M
/usr/local/bin/build-deploy-tool                                                                                                 28.9M         30.4M
/bin/envsubst                                                                                                                    2.2M          2M
/var/cache/apk/APKINDEX.a754f5eb.tar.gz                                                                                          1.6M          1.6M
/home/.cache/pip/http/c/7/4/6/4/c746471147afb0bfd92bc3b78e0c71a57f5fca217341ff44dad778f4                                         964.2K        964.2K
/var/cache/apk/APKINDEX.30e6f5af.tar.gz                                                                                          876.1K        873.7K
/var/cache/apk/APKINDEX.0488e555.tar.gz                                                                                          622.4K        622.5K
/home/.cache/pip/http/a/2/6/7/f/a267f54c19667a20e6416d2dc2a1df4a525eed802f0f2b538b654da1                                         194.8K        194.8K
/home/.cache/pip/http/5/3/e/c/9/53ec91543c24abb51ec1a0688696efb2dda5a2e5eeccb052b5e72e51                                         122.9K        122.9K
/home/.cache/pip/http/0/4/1/8/c/0418c83b80f7f7bfaec2738bfbbee53d2c1562196c0781702f6eddc8                                         111.8K        112.3K
/home/.cache/pip/wheels/b4/0f/9a/d6af48581dda678920fccfb734f5d9f827c6ed5b4074c7eda8/PyYAML-6.0-cp39-cp39-linux_x86_64.whl        44.3K         44.3K
/home/.cache/pip/http/0/f/d/7/b/0fd7b40ed8d3903b79c13551e53175e21f4a992ac413cc60c3060311                                         37.7K         37.8K
/home/.cache/pip/http/e/9/0/9/8/e909845026a6059abd99600e070e720b0e8069818f409a5176263a17                                         35.3K         35.4K
/home/.cache/pip/http/b/8/6/2/6/b862637a242a4033f1ba3be874e038f3a95ab29277da4c878f7c162d                                         31.7K         31.7K
/usr/lib/python3.9/site-packages/yaml/__pycache__/emitter.cpython-39.pyc                                                         24.7K         24.7K
/usr/lib/python3.9/site-packages/yaml/__pycache__/scanner.cpython-39.pyc                                                         24.7K         24.7K
/usr/lib/python3.9/site-packages/__pycache__/shyaml.cpython-39.pyc                                                               24K           24K
/usr/lib/python3.9/site-packages/argcomplete/__pycache__/__init__.cpython-39.pyc                                                 22.8K         22.8K
/home/.cache/pip/http/a/1/9/5/3/a19537d3cf37c122db841d6fe4cd322bc10d1a558bb00d146b85cb9a                                         20.4K         20.6K
/home/.cache/pip/http/7/0/f/7/5/70f7567560a574165fd2fbe67cceead060e3127d0317fa37288d1223                                         20.3K         20.4K
/usr/lib/python3.9/site-packages/yaml/__pycache__/constructor.cpython-39.pyc                                                     20.3K         20.3K
/home/.cache/pip/http/c/7/5/a/f/c75af6b872a08ae270eeaa198cc6b260b5ee75580a7aaf599478e9d3                                         17.7K         17.7K
/usr/lib/python3.9/site-packages/__pycache__/xmltodict.cpython-39.pyc                                                            14.1K         14.1K
/home/.cache/pip/http/8/2/d/5/b/82d5be6775b8495e315606f69dee203721426494022564d3923a04a1                                         12.8K         12.8K
/usr/lib/python3.9/site-packages/yaml/__pycache__/parser.cpython-39.pyc                                                          11.6K         11.6K
/home/.cache/pip/http/4/d/2/7/2/4d272e6453941ce8b0a37a02cdb1685fc612c33441fa74691fb40656                                         11.2K         11.2K
/usr/lib/python3.9/site-packages/yaml/__pycache__/__init__.cpython-39.pyc                                                        10.9K         10.9K
/home/.cache/pip/http/3/7/d/4/2/37d425c704668edcb7185bcf4d5536efdc91ff47084f033f24b8e66a                                         10.6K         10.7K
/usr/lib/python3.9/site-packages/yaml/__pycache__/representer.cpython-39.pyc                                                     9.8K          9.8K
/kubectl-build-deploy/build-deploy.sh                                                                                            8.2K          8.3K
/usr/lib/python3.9/site-packages/yq/__pycache__/__init__.cpython-39.pyc                                                          8.1K          8.1K
/home/.cache/pip/http/1/9/2/5/4/19254f602957de539747488c40c7b413a74ea22339b9ae95afc0c9f4                                         7.6K          7.6K
/usr/lib/python3.9/site-packages/argcomplete/__pycache__/my_argparse.cpython-39.pyc                                              6.4K          6.4K
/usr/lib/python3.9/site-packages/yq/__pycache__/loader.cpython-39.pyc                                                            6.2K          6.2K
/usr/lib/python3.9/site-packages/argcomplete/__pycache__/my_shlex.cpython-39.pyc                                                 6.1K          6.1K
/usr/lib/python3.9/site-packages/yaml/__pycache__/resolver.cpython-39.pyc                                                        5.4K          5.4K
/usr/lib/python3.9/site-packages/yaml/__pycache__/tokens.cpython-39.pyc                                                          4.8K          4.8K
/usr/lib/python3.9/site-packages/yaml/__pycache__/reader.cpython-39.pyc                                                          4.4K          4.4K
/usr/lib/python3.9/site-packages/argcomplete/__pycache__/completers.cpython-39.pyc                                               4.4K          4.4K
/usr/lib/python3.9/site-packages/yq/__pycache__/parser.cpython-39.pyc                                                            4.2K          4.2K
/usr/lib/python3.9/site-packages/argcomplete/__pycache__/shell_integration.cpython-39.pyc                                        4.1K          4.1K
/usr/lib/python3.9/site-packages/yaml/__pycache__/events.cpython-39.pyc                                                          3.9K          3.9K
/home/.cache/pip/http/3/3/2/7/e/3327e3666df596605e3bccaf3bbf488dd424f2d1b184f32bc12495e2                                         3.9K          3.9K
/usr/lib/python3.9/site-packages/yaml/__pycache__/composer.cpython-39.pyc                                                        3.5K          3.5K
/usr/lib/python3.9/site-packages/yaml/__pycache__/cyaml.cpython-39.pyc                                                           3.3K          3.3K
/usr/lib/python3.9/site-packages/yaml/__pycache__/serializer.cpython-39.pyc                                                      3.2K          3.2K
/home/.cache/pip/http/7/1/4/e/0/714e0002ced5d29140019235c13c7dd0206bca85c718ffb161201577                                         2.9K          2.9K
/usr/lib/python3.9/site-packages/yq/__pycache__/dumper.cpython-39.pyc                                                            2.7K          2.7K
/usr/lib/python3.9/site-packages/argcomplete/__pycache__/_check_module.cpython-39.pyc                                            2.4K          2.4K
/usr/lib/python3.9/site-packages/yaml/__pycache__/error.cpython-39.pyc                                                           2.3K          2.3K
/usr/lib/python3.9/site-packages/yaml/__pycache__/loader.cpython-39.pyc                                                          2.1K          2.1K
/usr/lib/python3.9/site-packages/argcomplete/__pycache__/_check_console_script.cpython-39.pyc                                    1.9K          1.9K
/usr/lib/python3.9/site-packages/yaml/__pycache__/dumper.cpython-39.pyc                                                          1.7K          1.7K
/usr/lib/python3.9/site-packages/yaml/__pycache__/nodes.cpython-39.pyc                                                           1.7K          1.7K
/usr/lib/python3.9/site-packages/_yaml/__pycache__/__init__.cpython-39.pyc                                                       705B          705B
/usr/lib/python3.9/site-packages/yq/__pycache__/version.cpython-39.pyc                                                           232B          232B
/usr/lib/python3.9/site-packages/yq/__pycache__/__main__.cpython-39.pyc                                                          215B          215B
/home/.cache/pip/selfcheck/241e69162522ccf5846a2f42ebc24b17464915a155679666b89a9f31                                              74B           74B

```

### CODE REVIEW

**Comment by tobybellwood** [comment]
ok - i've built and tested this in my fork - tag builds work as expected:

for a tag push - create :tag and :latest images
for a non-tag push to main - create :tag-build, :edge and :main images

The version reported by the version command is the same as the tag
```
tobybellwood@pop-os $ docker run --entrypoint /bin/bash tobybellwood/build-deploy-tool:v2.9.1 -c 'build-deploy-tool version'
build-deploy-tool v2.9.1 (built: 2022-08-09T23:15:58+0000 / go 1.17)
tobybellwood@pop-os $ docker run --entrypoint /bin/bash tobybellwood/build-deploy-tool:latest -c 'build-deploy-tool version'
build-deploy-tool v2.9.1 (built: 2022-08-09T23:15:58+0000 / go 1.17)
tobybellwood@pop-os $ docker run --entrypoint /bin/bash tobybellwood/build-deploy-tool:v2.9.1-093f96e6 -c 'build-deploy-tool version'
build-deploy-tool v2.9.1+093f96e6 (built: 2022-08-09T23:24:01+0000 / go 1.17)
tobybellwood@pop-os $ docker run --entrypoint /bin/bash tobybellwood/build-deploy-tool:edge -c 'build-deploy-tool version'
build-deploy-tool v2.9.1+093f96e6 (built: 2022-08-09T23:24:01+0000 / go 1.17)
tobybellwood@pop-os $ docker run --entrypoint /bin/bash tobybellwood/build-deploy-tool:main -c 'build-deploy-tool version'
build-deploy-tool v2.9.1+093f96e6 (built: 2022-08-09T23:24:01+0000 / go 1.17)
```


image

**Comment by shreddedbacon** [comment]
Are we good to squash merge this now so we can start bringing other PRs in?

**Comment by tobybellwood** [comment]
yes - it is the same as 2.9.2 which although published, isn't released just yet, but this is fine to merge - and maybe then tag v2.9.2 to match?

**Comment by shreddedbacon** [comment]
Do we need to tag this at all with 2.9.2? Aren't we moving away from versioning with lagoon-core?

**Pull request merged**
